export const allProducts = [
  {
    id: 1,
    title: "Aethelgard: The Dragon's Fury",
    price: 120.69,
    category: "action",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053672/Google_AI_Studio_2025-10-26T09_16_12.887Z_lqcjox.png",
    description:
      "Unleash the legend in this epic fantasy action RPG. Battle dragons, forge alliances, and become the hero Aethelgard needs. Featuring intense combat, deep character customization, and a vast open world to explore.",
    rating: 3.8,
    releaseDate: "2024-03-15",
    developer: "Dragonforge Studios",
    publisher: "Epic Legends Publishing",
    tags: ["Action", "RPG", "Fantasy", "Open World"],
    isFree: false,
  },
  {
    id: 2,
    title: "Shadow Blade: Eternal Night",
    price: 152.47,
    category: "action",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053693/Google_AI_Studio_2025-10-26T08_40_54.495Z_ebvaka.png",
    description:
      "Master the art of stealth and combat in this dark fantasy action game. Wield ancient shadow magic, navigate treacherous landscapes, and uncover the secrets of the Eternal Night.",
    rating: 4.4,
    releaseDate: "2024-01-22",
    developer: "Shadow Works Games",
    publisher: "Dark Arts Interactive",
    tags: ["Action", "Stealth", "Fantasy", "Dark"],
    isFree: false,
  },
  {
    id: 3,
    title: "Iron Vanguard",
    price: 379.09,
    category: "action",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053690/Google_AI_Studio_2025-10-26T08_43_34.698Z_waqwbz.png",
    description:
      "Lead the Iron Vanguard in this intense action strategy game. Command elite warriors, upgrade your fortress, and defend humanity against an ancient evil awakening from slumber.",
    rating: 4.3,
    releaseDate: "2023-11-08",
    developer: "Steel Legion Studios",
    publisher: "Warrior Games",
    tags: ["Action", "Strategy", "Medieval", "War"],
    isFree: false,
  },
  {
    id: 4,
    title: "Crimson Reaper",
    price: 373.77,
    category: "action",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053688/Google_AI_Studio_2025-10-26T09_12_00.708Z_amtrqq.png",
    description:
      "Play as the legendary Crimson Reaper in this free-to-play action brawler. Master deadly scythe combat, collect souls to upgrade abilities, and challenge players worldwide in intense PvP arenas.",
    rating: 2.1,
    releaseDate: "2024-06-01",
    developer: "Blood Moon Studios",
    publisher: "FreePlay Games",
    tags: ["Action", "Brawler", "Free to Play", "Multiplayer"],
    isFree: false,
  },
  {
    id: 5,
    title: "Storm Breaker",
    price: 109.08,
    category: "action",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053686/Google_AI_Studio_2025-10-26T08_39_43.810Z_piw604.png",
    description:
      "Harness the power of lightning in Storm Breaker, an electrifying action adventure. Control weather elements, explore storm-ravaged realms, and battle elemental titans threatening the world.",
    rating: 3.8,
    releaseDate: "2024-08-20",
    developer: "Thunderbolt Interactive",
    publisher: "Elemental Entertainment",
    tags: ["Action", "Adventure", "Fantasy", "Magic"],
    isFree: false,
  },
  {
    id: 6,
    title: "Ashen Legacy",
    price: 131.88,
    category: "action",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053679/Google_AI_Studio_2025-10-26T09_13_55.545Z_dkwnyk.png",
    description:
      "In a world consumed by ash, fight to restore the ancient legacy. Ashen Legacy combines Souls-like combat with deep storytelling, challenging boss battles, and atmospheric exploration.",
    rating: 3.6,
    releaseDate: "2023-09-14",
    developer: "Ashfall Studios",
    publisher: "Legacy Games",
    tags: ["Action", "Souls-like", "Dark Fantasy", "Difficult"],
    isFree: false,
  },
  {
    id: 7,
    title: "Void Walker",
    price: 77.85,
    category: "action",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053676/Google_AI_Studio_2025-10-26T09_24_00.246Z_zit0my.png",
    description:
      "Step through the void in this dimension-hopping action game. Switch between parallel worlds to solve puzzles, defeat interdimensional threats, and uncover the mystery of the Void.",
    rating: 2.9,
    releaseDate: "2024-04-10",
    developer: "Dimensional Games",
    publisher: "Cosmic Interactive",
    tags: ["Action", "Puzzle", "Sci-Fi", "Free to Play"],
    isFree: false,
  },
  {
    id: 8,
    title: "Ember Knight",
    price: 343.23,
    category: "action",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053674/Google_AI_Studio_2025-10-26T09_14_56.424Z_icspty.png",
    description:
      "Rise as the Ember Knight and wield the power of eternal flames. This cinematic action RPG features fluid combat, stunning visuals, and an epic tale of redemption in a burning world.",
    rating: 2.4,
    releaseDate: "2024-07-05",
    developer: "Phoenix Rising Studios",
    publisher: "Inferno Entertainment",
    tags: ["Action", "RPG", "Fantasy", "Story Rich"],
    isFree: false,
  },
  {
    id: 9,
    title: "Velocity X-Treme",
    price: 55.38,
    category: "racing",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053303/Gemini_Generated_Image_73vfyf73vfyf73vf_rhr6i3.png",
    description:
      "Experience the ultimate futuristic racing in Velocity X-Treme. Pilot anti-gravity vehicles through neon-lit cityscapes, master impossible tracks, and compete in high-stakes tournaments across the galaxy.",
    rating: 2,
    releaseDate: "2024-03-20",
    developer: "Nitro Forge Studios",
    publisher: "Speed Demon Games",
    tags: ["Racing", "Futuristic", "Arcade", "Multiplayer"],
    isFree: false,
  },
  {
    id: 10,
    title: "Drift King Championship",
    price: 370.82,
    category: "racing",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053302/Gemini_Generated_Image_5sbska5sbska5sbs_y2tcxp.png",
    description:
      "Master the art of drifting in this authentic Japanese street racing experience. Customize your ride, perfect your technique on mountain passes, and become the ultimate Drift King.",
    rating: 3.1,
    releaseDate: "2023-11-15",
    developer: "Tokyo Drift Studios",
    publisher: "Rising Sun Interactive",
    tags: ["Racing", "Drifting", "Simulation", "Japan"],
    isFree: false,
  },
  {
    id: 11,
    title: "Off-Road Thunder",
    price: 114.73,
    category: "racing",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053301/Gemini_Generated_Image_j9gyvkj9gyvkj9gy_kextsp.png",
    description:
      "Conquer extreme terrain in Off-Road Thunder. Race through mud, sand, snow, and rocky landscapes with customizable 4x4s, rally cars, and monster trucks in this adrenaline-fueled off-road adventure.",
    rating: 4.8,
    releaseDate: "2024-01-08",
    developer: "Terrain Masters",
    publisher: "Wild Racing Games",
    tags: ["Racing", "Off-Road", "4x4", "Rally"],
    isFree: false,
  },
  {
    id: 12,
    title: "Neon Nights Racing",
    price: 111.88,
    category: "racing",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053300/Gemini_Generated_Image_uzaia3uzaia3uzai_tjonfz.png",
    description:
      "Dive into the cyberpunk underground racing scene in Neon Nights. Customize your neon-lit street machine, evade corporate security, and rise through the ranks in this free-to-play street racing phenomenon.",
    rating: 3.1,
    releaseDate: "2024-06-22",
    developer: "Cyber Studios",
    publisher: "Neon Entertainment",
    tags: ["Racing", "Street Racing", "Cyberpunk", "Free to Play"],
    isFree: false,
  },
  {
    id: 13,
    title: "Grand Prix Legends",
    price: 0,
    category: "racing",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053300/Gemini_Generated_Image_v2wbqqv2wbqqv2wb_tpzlbh.png",
    description:
      "Experience the pinnacle of motorsport in Grand Prix Legends. Drive officially licensed Formula 1 cars on legendary circuits worldwide with ultra-realistic physics and stunning broadcast-quality presentation.",
    rating: 1.7,
    releaseDate: "2024-08-10",
    developer: "Pinnacle Racing Games",
    publisher: "Speed League Entertainment",
    tags: ["Racing", "Formula 1", "Simulation", "Realistic"],
    isFree: true,
  },
  {
    id: 14,
    title: "Chronicles of Aethelgard",
    price: 0,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053420/Gemini_Generated_Image_lrxf7glrxf7glrxf_qlmmsl.png",
    description:
      "Embark on an epic journey through the mystical lands of Aethelgard. Master ancient dragon magic, forge legendary alliances, and shape the fate of kingdoms in this sprawling fantasy RPG with deep character customization and branching storylines.",
    rating: 3.9,
    releaseDate: "2024-02-14",
    developer: "Dragon Lore Studios",
    publisher: "Epic Tales Publishing",
    tags: ["RPG", "Fantasy", "Dragon", "Open World"],
    isFree: true,
  },
  {
    id: 15,
    title: "Shadow Realm Saga",
    price: 0,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053419/Gemini_Generated_Image_cpgcdycpgcdycpgc_v2qclb.png",
    description:
      "Venture into the Shadow Realm where darkness holds ancient secrets. Combine stealth and magic in this dark fantasy RPG featuring morally complex choices, shadow manipulation powers, and a hauntingly beautiful world.",
    rating: 4.7,
    releaseDate: "2023-10-30",
    developer: "Umbra Interactive",
    publisher: "Dark Fantasy Games",
    tags: ["RPG", "Dark Fantasy", "Stealth", "Magic"],
    isFree: true,
  },
  {
    id: 16,
    title: "Eternal Dragon Quest",
    price: 0,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053417/Gemini_Generated_Image_96v7j296v7j296v7_eolac9.png",
    description:
      "A classic JRPG-inspired adventure awaits! Gather your party of heroes, battle fearsome monsters, and uncover the mystery of the Eternal Dragon. Features turn-based combat, beautiful pixel art, and an emotional story.",
    rating: 2,
    releaseDate: "2024-05-20",
    developer: "Retro Dream Studios",
    publisher: "Questline Entertainment",
    tags: ["RPG", "JRPG", "Turn-Based", "Retro"],
    isFree: true,
  },
  {
    id: 17,
    title: "Mystic Legends",
    price: 498.14,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053416/Gemini_Generated_Image_x4szhrx4szhrx4sz_ziqmg2.png",
    description:
      "Master the arcane arts in Mystic Legends! Craft powerful spells, tame magical creatures, and uncover ancient mysteries. Features an innovative spell-crafting system and a vibrant world full of wonder and danger.",
    rating: 2.6,
    releaseDate: "2024-01-15",
    developer: "Arcane Works",
    publisher: "Mystic Entertainment",
    tags: ["RPG", "Magic", "Spell Crafting", "Fantasy"],
    isFree: false,
  },
  {
    id: 18,
    title: "Realm of Shadows",
    price: 181.49,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053414/Gemini_Generated_Image_764i2x764i2x764i_cx3oqe.png",
    description:
      "Enter the unforgiving Realm of Shadows, where every battle could be your last. This challenging Souls-like RPG features precise combat, atmospheric exploration, and epic boss battles that will test your skills.",
    rating: 1.9,
    releaseDate: "2023-09-22",
    developer: "Grimlight Studios",
    publisher: "Hardcore Games",
    tags: ["RPG", "Souls-like", "Difficult", "Dark"],
    isFree: false,
  },
  {
    id: 19,
    title: "Ancient Prophecy",
    price: 123.66,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053412/Gemini_Generated_Image_2k6ak02k6ak02k6a_e3beho.png",
    description:
      "Your choices shape the world in Ancient Prophecy. This narrative-driven RPG features morally complex decisions, multiple endings, and a living world that reacts to your actions. Every choice has consequences.",
    rating: 2.8,
    releaseDate: "2024-07-08",
    developer: "Storyweaver Interactive",
    publisher: "Narrative First",
    tags: ["RPG", "Story Rich", "Choices Matter", "Multiple Endings"],
    isFree: false,
  },
  {
    id: 20,
    title: "Kingdom of Ash",
    price: 8.7,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053411/Gemini_Generated_Image_ng2qdpng2qdpng2q_yktgtv.png",
    description:
      "Survive in a world consumed by ash and darkness. This free-to-play post-apocalyptic fantasy RPG features base building, scavenging, and intense combat as you fight to restore hope to a broken world.",
    rating: 3.7,
    releaseDate: "2024-04-01",
    developer: "Ashen Realms Studio",
    publisher: "FreeQuest Games",
    tags: ["RPG", "Post-Apocalyptic", "Survival", "Free to Play"],
    isFree: false,
  },
  {
    id: 21,
    title: "Celestial Warriors",
    price: 289.68,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053409/Gemini_Generated_Image_ray107ray107ray1_qjarx8.png",
    description:
      "Ascend to divine power as a Celestial Warrior! Wield heavenly weapons, command angelic allies, and battle demonic forces threatening the mortal realm. Features fast-paced action combat and divine skill trees.",
    rating: 4.5,
    releaseDate: "2023-12-12",
    developer: "Heavenly Forge",
    publisher: "Divine Entertainment",
    tags: ["RPG", "Action", "Angels", "Heavenly"],
    isFree: false,
  },
  {
    id: 22,
    title: "Forgotten Realms",
    price: 226,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053408/Gemini_Generated_Image_wa62hpwa62hpwa62_dhn9ci.png",
    description:
      "Explore vast uncharted territories in Forgotten Realms. This open-world RPG emphasizes discovery, with hidden dungeons, ancient ruins, and secrets waiting around every corner. Your adventure begins where the map ends.",
    rating: 3.6,
    releaseDate: "2024-03-05",
    developer: "Explorer Studios",
    publisher: "Discovery Games",
    tags: ["RPG", "Open World", "Exploration", "Adventure"],
    isFree: false,
  },
  {
    id: 23,
    title: "Soul Reaver Chronicles",
    price: 0,
    category: "rpg",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053407/Gemini_Generated_Image_di40bzdi40bzdi40_jbkfct.png",
    description:
      "Harvest souls and unlock forbidden powers in Soul Reaver Chronicles. This dark RPG features a unique soul-capture mechanic, necromantic abilities, and a gripping tale of redemption and corruption.",
    rating: 4.9,
    releaseDate: "2023-11-28",
    developer: "Soulbound Games",
    publisher: "Dark Arts Publishing",
    tags: ["RPG", "Dark", "Souls", "Necromancy"],
    isFree: true,
  },
  {
    id: 24,
    title: "Tactical Ops: Elite Squad",
    price: 225.62,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053720/Google_AI_Studio_2025-10-26T08_45_35.446Z_bci0wv.png",
    description:
      "Lead an elite tactical squad through high-stakes military operations. Plan your approach, coordinate with teammates, and execute precision strikes in this realistic tactical shooter.",
    rating: 2.5,
    releaseDate: "2024-02-10",
    developer: "Tactical Dynamics",
    publisher: "Elite Force Games",
    tags: ["Shooter", "Tactical", "Military", "Team-Based"],
    isFree: false,
  },
  {
    id: 25,
    title: "Cyber Hunter 2077",
    price: 193.06,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053717/Google_AI_Studio_2025-10-26T08_46_23.022Z_blawuo.png",
    description:
      "Hunt targets in a neon-drenched cyberpunk metropolis. Customize your cybernetic enhancements, master futuristic weaponry, and uncover conspiracies in this stylish sci-fi shooter.",
    rating: 1.6,
    releaseDate: "2023-12-01",
    developer: "Neon Forge Studios",
    publisher: "Cyber Entertainment",
    tags: ["Shooter", "Cyberpunk", "Sci-Fi", "Futuristic"],
    isFree: false,
  },
  {
    id: 26,
    title: "Zombie Outbreak Protocol",
    price: 0,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053593/Google_AI_Studio_2025-10-26T09_27_09.382Z_io1xap.png",
    description:
      "Survive the undead apocalypse in this free-to-play zombie shooter. Scavenge for weapons, fortify safe zones, and fight off hordes of the infected with friends in intense co-op gameplay.",
    rating: 4.1,
    releaseDate: "2024-04-15",
    developer: "Outbreak Studios",
    publisher: "Survival Games Inc",
    tags: ["Shooter", "Zombie", "Survival", "Free to Play"],
    isFree: true,
  },
  {
    id: 27,
    title: "Space Marine Vanguard",
    price: 225.7,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053590/Google_AI_Studio_2025-10-26T09_26_46.509Z_asme3d.png",
    description:
      "Join the elite Space Marine Vanguard and defend humanity across the galaxy. Experience epic battles against alien hordes with powerful weapons and devastating abilities in this sci-fi action shooter.",
    rating: 4.1,
    releaseDate: "2024-01-20",
    developer: "Cosmic Forge",
    publisher: "Galactic Entertainment",
    tags: ["Shooter", "Sci-Fi", "Space", "Action"],
    isFree: false,
  },
  {
    id: 28,
    title: "Stealth Phantom",
    price: 0,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053588/Google_AI_Studio_2025-10-26T09_27_25.611Z_fowoc2.png",
    description:
      "Become the ultimate silent assassin in Stealth Phantom. Use shadows, gadgets, and precision marksmanship to eliminate targets without detection in this stealth-focused shooter.",
    rating: 3.8,
    releaseDate: "2023-11-05",
    developer: "Shadow Ops Studios",
    publisher: "Phantom Games",
    tags: ["Shooter", "Stealth", "Assassin", "Tactical"],
    isFree: true,
  },
  {
    id: 29,
    title: "Arena Champions",
    price: 0,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053561/Google_AI_Studio_2025-10-26T09_27_40.253Z_i8ziwy.png",
    description:
      "Compete in high-octane arena battles in this free-to-play FPS. Master unique champions, each with special abilities, and dominate the leaderboard in fast-paced multiplayer matches.",
    rating: 4.5,
    releaseDate: "2024-05-01",
    developer: "Arena Forge",
    publisher: "Champion Games",
    tags: ["Shooter", "Arena", "FPS", "Free to Play"],
    isFree: true,
  },
  {
    id: 30,
    title: "Battlefield: Global War",
    price: 185.27,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053559/Google_AI_Studio_2025-10-26T09_32_32.696Z_sbnofx.png",
    description:
      "Experience massive 64-player battles across global conflict zones. Command vehicles, capture objectives, and work with your squad in this large-scale warfare shooter.",
    rating: 2.3,
    releaseDate: "2024-03-15",
    developer: "Warzone Studios",
    publisher: "Global Conflict Games",
    tags: ["Shooter", "Warfare", "Large Scale", "Multiplayer"],
    isFree: false,
  },
  {
    id: 31,
    title: "Neon Strike Force",
    price: 0,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053557/Google_AI_Studio_2025-10-26T09_32_40.285Z_i7dgah.png",
    description:
      "Lead a cyberpunk tactical team in neon-soaked combat zones. Coordinate squad tactics, deploy drones, and hack enemy systems in this stylish team-based shooter.",
    rating: 4.8,
    releaseDate: "2023-10-20",
    developer: "Neon Tactical Studios",
    publisher: "Cyber Force Games",
    tags: ["Shooter", "Cyberpunk", "Tactical", "Team-Based"],
    isFree: true,
  },
  {
    id: 32,
    title: "Survivalist: Last Stand",
    price: 445.67,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053555/Google_AI_Studio_2025-10-26T09_33_19.724Z_wchnhg.png",
    description:
      "Fight to survive in a post-apocalyptic wasteland. Scavenge for weapons and supplies, build defenses, and defend against hostile factions in this intense survival shooter.",
    rating: 5,
    releaseDate: "2024-06-10",
    developer: "Wasteland Studios",
    publisher: "Survival Games",
    tags: ["Shooter", "Survival", "Post-Apocalyptic", "Base Building"],
    isFree: false,
  },
  {
    id: 33,
    title: "Ghost Recon: Shadow Unit",
    price: 0,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053553/Google_AI_Studio_2025-10-26T09_33_41.703Z_n5huv4.png",
    description:
      "Join the elite Shadow Unit in this free-to-play tactical shooter. Execute covert operations, utilize advanced military tech, and eliminate high-value targets around the world.",
    rating: 4.4,
    releaseDate: "2024-02-28",
    developer: "Spec Ops Interactive",
    publisher: "Tactical Entertainment",
    tags: ["Shooter", "Tactical", "Special Ops", "Free to Play"],
    isFree: true,
  },
  {
    id: 34,
    title: "Mech Warrior Arena",
    price: 238.29,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053551/Gemini_Generated_Image_j1j3goj1j3goj1j3_d4kexe.png",
    description:
      "Pilot customizable war machines in explosive mech combat. Choose your chassis, loadouts, and tactics to dominate the arena in this intense mechanized shooter.",
    rating: 3.1,
    releaseDate: "2024-04-22",
    developer: "Mech Forge Studios",
    publisher: "Iron Giant Games",
    tags: ["Shooter", "Mech", "Robot", "Arena"],
    isFree: false,
  },
  {
    id: 35,
    title: "Urban Warfare",
    price: 343.02,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053549/Gemini_Generated_Image_ql8ffcql8ffcql8f_sarq4o.png",
    description:
      "Engage in intense city-based combat across detailed urban environments. Navigate streets, buildings, and rooftops while fighting enemy forces in this realistic modern warfare shooter.",
    rating: 4.2,
    releaseDate: "2023-12-15",
    developer: "City Combat Studios",
    publisher: "Urban Games",
    tags: ["Shooter", "Urban", "Modern Warfare", "Realistic"],
    isFree: false,
  },
  {
    id: 36,
    title: "Alien Invasion Defense",
    price: 221.83,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053547/Google_AI_Studio_2025-10-26T09_34_51.474Z_lumdse.png",
    description:
      "Defend Earth from extraterrestrial invasion in this action-packed sci-fi shooter. Use advanced weaponry, deploy defensive structures, and repel waves of alien attackers.",
    rating: 4.6,
    releaseDate: "2024-01-30",
    developer: "Xeno Defense Studios",
    publisher: "Planetary Defense Games",
    tags: ["Shooter", "Alien", "Sci-Fi", "Defense"],
    isFree: false,
  },
  {
    id: 37,
    title: "Sniper: Phantom Ops",
    price: 133.99,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053545/Google_AI_Studio_2025-10-26T09_34_25.742Z_r9nz54.png",
    description:
      "Master the art of long-range combat in this precision sniper shooter. Calculate wind, distance, and bullet drop as you eliminate targets from extreme distances across exotic locations.",
    rating: 2.9,
    releaseDate: "2024-05-20",
    developer: "Precision Studios",
    publisher: "Sniper Elite Games",
    tags: ["Shooter", "Sniper", "Tactical", "Precision"],
    isFree: false,
  },
  {
    id: 38,
    title: "Rogue Agent",
    price: 321.34,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053481/Gemini_Generated_Image_or8vakor8vakor8v_emsg4r.png",
    description:
      "Go rogue as a disavowed spy in this free-to-play espionage shooter. Infiltrate enemy bases, gather intel, and take down criminal organizations with deadly precision.",
    rating: 2.3,
    releaseDate: "2023-09-10",
    developer: "Covert Studios",
    publisher: "Spy Games International",
    tags: ["Shooter", "Espionage", "Spy", "Free to Play"],
    isFree: false,
  },
  {
    id: 39,
    title: "Doomsday Protocol",
    price: 205.71,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053479/Gemini_Generated_Image_4cewdm4cewdm4cew_sbivg5.png",
    description:
      "Execute the Doomsday Protocol in this intense post-apocalyptic shooter. Scavenge weapons, form alliances, and fight for survival in a world on the brink of extinction.",
    rating: 1.6,
    releaseDate: "2024-03-08",
    developer: "Apocalypse Studios",
    publisher: "End Times Games",
    tags: ["Shooter", "Post-Apocalyptic", "Survival", "Action"],
    isFree: false,
  },
  {
    id: 40,
    title: "Plasma Strike",
    price: 0,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053478/Gemini_Generated_Image_cfthdrcfthdrcfth_idjfrx.png",
    description:
      "Wield devastating plasma weapons in this futuristic energy shooter. Customize your arsenal of high-tech weaponry and battle across alien worlds with cutting-edge firepower.",
    rating: 3.2,
    releaseDate: "2024-02-14",
    developer: "Energy Weapons Labs",
    publisher: "Futuristic Games",
    tags: ["Shooter", "Futuristic", "Energy Weapons", "Sci-Fi"],
    isFree: true,
  },
  {
    id: 41,
    title: "Covert Operations",
    price: 0,
    category: "shooting",
    imageUrl:
      "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053476/Gemini_Generated_Image_avd85aavd85aavd8_jyyzlg.png",
    description:
      "Lead black ops missions across the globe in this premium tactical shooter. Plan infiltrations, eliminate targets, and extract without a trace in this high-stakes espionage experience.",
    rating: 4.1,
    releaseDate: "2024-07-01",
    developer: "Black Ops Studios",
    publisher: "Elite Operations Games",
    tags: ["Shooter", "Black Ops", "Tactical", "Stealth"],
    isFree: true,
  },
  {
    id: 42,
    title: "Super Slam Basketball 24",
    price: 152.94,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056948/2022577943464644608_qthkpn.jpg",
    description: "Experience the most realistic basketball simulation ever created. Build your dynasty, compete in online leagues, and lead your team to championship glory with stunning graphics and authentic gameplay.",
    rating: 2.7,
    releaseDate: "2023-10-15",
    developer: "Hoops Studios",
    publisher: "Slam Dunk Games",
    tags: ["Sports", "Basketball", "Simulation", "Multiplayer"],
    isFree: false,
  },
  {
    id: 43,
    title: "Ultimate Soccer Championship",
    price: 381.71,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056947/2022578599931940864_kwx9is.jpg",
    description: "The beautiful game reimagined. Control every aspect of your club from tactics to transfers in this comprehensive football management and simulation experience featuring over 700 licensed teams.",
    rating: 2.1,
    releaseDate: "2023-09-28",
    developer: "Pitch Perfect Studios",
    publisher: "Goal Scorer Entertainment",
    tags: ["Sports", "Soccer", "Football", "Management"],
    isFree: false,
  },
  {
    id: 44,
    title: "Grand Slam Tennis Tour",
    price: 362.09,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056946/2022578408575209472_wofee4.jpg",
    description: "Serve, volley, and smash your way to Grand Slam glory. Compete on all four major tournaments with realistic physics and career mode that lets you create your tennis legend from junior to champion.",
    rating: 3.2,
    releaseDate: "2024-05-12",
    developer: "Ace Studios",
    publisher: "Match Point Games",
    tags: ["Sports", "Tennis", "Career Mode", "Realistic"],
    isFree: false,
  },
  {
    id: 45,
    title: "Extreme Skateboarding X",
    price: 381.7,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056945/2022579240716734464_zlql9f.jpg",
    description: "Free-to-play skateboarding action with massive open worlds to explore. Master hundreds of tricks, compete in online events, and customize your skater with the latest gear and apparel.",
    rating: 4.3,
    releaseDate: "2024-03-20",
    developer: "Grind Studios",
    publisher: "Skate Life Games",
    tags: ["Sports", "Skateboarding", "Open World", "Free to Play"],
    isFree: false,
  },
  {
    id: 46,
    title: "Pro Golf Masters",
    price: 18.55,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056944/2022579839738843136_cjxfa5.jpg",
    description: "Tee off on world-famous courses with photorealistic graphics. Master your swing mechanics, compete in PGA tournaments, and challenge friends in this authentic golf simulation.",
    rating: 2.8,
    releaseDate: "2023-08-18",
    developer: "Fairway Interactive",
    publisher: "Green Jacket Games",
    tags: ["Sports", "Golf", "Simulation", "Realistic"],
    isFree: false,
  },
  {
    id: 47,
    title: "Heavyweight Boxing Championship",
    price: 92.52,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056944/2022580022153318400_vahjla.jpg",
    description: "Step into the ring and fight for the heavyweight title. Featuring realistic boxing mechanics, career mode with rivalries, and legendary boxers to challenge in this intense combat sports experience.",
    rating: 4.6,
    releaseDate: "2024-01-25",
    developer: "Knockout Studios",
    publisher: "Champion Belt Games",
    tags: ["Sports", "Boxing", "Combat", "Career Mode"],
    isFree: false,
  },
  {
    id: 48,
    title: "Extreme Snowboarding",
    price: 393.25,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056944/2022580200302186496_huacou.jpg",
    description: "Shred the slopes in this adrenaline-pumping snowboarding game. Master extreme tricks, race down mountains, and explore massive alpine resorts in solo or multiplayer modes.",
    rating: 2.8,
    releaseDate: "2023-12-10",
    developer: "Powder Studios",
    publisher: "Winter Sports Interactive",
    tags: ["Sports", "Snowboarding", "Extreme", "Winter"],
    isFree: false,
  },
  {
    id: 49,
    title: "Formula Racing Pro",
    price: 252.43,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056942/2022582550966308864_wh1cdy.jpg",
    description: "The ultimate motorsport simulation with all official F1 teams, drivers, and circuits. Experience ultra-realistic driving physics, dynamic weather, and intense championship battles.",
    rating: 3.4,
    releaseDate: "2024-07-05",
    developer: "Pit Lane Studios",
    publisher: "Speed Demon Games",
    tags: ["Sports", "Racing", "Formula 1", "Simulation"],
    isFree: false,
  },
  {
    id: 50,
    title: "Beach Volleyball Masters",
    price: 60.77,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056942/2022582717127856128_zexv7t.jpg",
    description: "Spike, set, and dig your way to victory in this free-to-play beach volleyball game. Compete in tournaments worldwide with realistic physics and beautiful tropical locations.",
    rating: 4.9,
    releaseDate: "2024-06-15",
    developer: "Sand Court Studios",
    publisher: "Summer Games",
    tags: ["Sports", "Volleyball", "Beach", "Free to Play"],
    isFree: false,
  },
  {
    id: 51,
    title: "Ice Hockey Elite",
    price: 315.86,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771056942/2022584689121824768_rhrsxr.jpg",
    description: "Hit the ice in the most authentic hockey simulation. Control every aspect of your franchise, from drafting prospects to calling plays, with realistic physics and NHL licensing.",
    rating: 3.9,
    releaseDate: "2023-11-20",
    developer: "Frozen Pond Studios",
    publisher: "Slap Shot Games",
    tags: ["Sports", "Hockey", "Ice", "Simulation"],
    isFree: false,
  },
  {
    id: 52,
    title: "MMA Fighter Championship",
    price: 479.59,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771054927/Gemini_Generated_Image_og9s9vog9s9vog9s_cffsrh.png",
    description: "Step into the octagon and fight for the championship belt. Master multiple martial arts disciplines, build your fighter's career, and compete in realistic MMA battles.",
    rating: 1.7,
    releaseDate: "2024-02-28",
    developer: "Cage Fight Studios",
    publisher: "Combat Sports Interactive",
    tags: ["Sports", "MMA", "Fighting", "Combat"],
    isFree: false,
  },
  {
    id: 53,
    title: "Extreme Parkour Challenge",
    price: 0,
    category: "sports",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771054927/Gemini_Generated_Image_t8blkot8blkot8bl_wfxzyd.png",
    description: "Run, jump, and flip through urban environments in this parkour sports game. Master fluid movement mechanics, compete in time trials, and explore massive city landscapes.",
    rating: 2.8,
    releaseDate: "2024-04-08",
    developer: "Freestyle Studios",
    publisher: "Urban Movement Games",
    tags: ["Sports", "Parkour", "Free Running", "Urban"],
    isFree: true,
  },
  {
    id: 54,
    title: "Empire Builder: Rise of Civilizations",
    price: 242.27,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053526/Gemini_Generated_Image_wg2tn5wg2tn5wg2t_ms4f3n.png",
    description: "Lead your civilization from ancient times to the space age in this epic 4X strategy game. Build cities, research technologies, wage wars, and forge diplomatic alliances to dominate the world.",
    rating: 2,
    releaseDate: "2024-02-15",
    developer: "Civilization Forge",
    publisher: "Empire Games",
    tags: ["Strategy", "4X", "Civilization", "Historical"],
    isFree: false,
  },
  {
    id: 55,
    title: "War Commander: Global Conflict",
    price: 0,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053524/Gemini_Generated_Image_yza6upyza6upyza6_dqaqzi.png",
    description: "Command armies in massive real-time strategy battles across the globe. Deploy tanks, aircraft, and infantry in tactical warfare with realistic physics and destructible environments.",
    rating: 3.2,
    releaseDate: "2023-11-30",
    developer: "Tactical Dynamics",
    publisher: "War Games International",
    tags: ["Strategy", "RTS", "Military", "War"],
    isFree: true,
  },
  {
    id: 56,
    title: "Space Colony Alpha",
    price: 495.06,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053523/Gemini_Generated_Image_3o5z5d3o5z5d3o5z_srhj9p.png",
    description: "Build and manage a thriving space colony on distant planets in this free-to-play sci-fi strategy game. Balance resources, research alien technologies, and defend against cosmic threats.",
    rating: 2.9,
    releaseDate: "2024-05-20",
    developer: "Cosmic Forge Studios",
    publisher: "Star Colony Games",
    tags: ["Strategy", "Sci-Fi", "Colony", "Free to Play"],
    isFree: false,
  },
  {
    id: 57,
    title: "Medieval Kingdoms: Total War",
    price: 23.87,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053521/Gemini_Generated_Image_7wb2yh7wb2yh7wb2_tihmvn.png",
    description: "Experience grand medieval warfare with massive battles and deep kingdom management. Command armies of knights and archers while managing economy, diplomacy, and castle sieges.",
    rating: 1.6,
    releaseDate: "2024-01-10",
    developer: "Castle Siege Studios",
    publisher: "Medieval Games",
    tags: ["Strategy", "Medieval", "Warfare", "RTS"],
    isFree: false,
  },
  {
    id: 58,
    title: "Cyber Defense Protocol",
    price: 0,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053519/Gemini_Generated_Image_122wo3122wo3122w_xfuvlp.png",
    description: "Defend corporate networks from cyber attacks in this tower defense strategy game. Deploy firewalls, antivirus programs, and counter-hackers to protect valuable data from hostile intrusions.",
    rating: 3.7,
    releaseDate: "2023-09-15",
    developer: "Cyber Security Games",
    publisher: "Digital Defense",
    tags: ["Strategy", "Tower Defense", "Cyberpunk", "Hacking"],
    isFree: true,
  },
  {
    id: 59,
    title: "Trade Empire: Silk Road",
    price: 159.43,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053518/Gemini_Generated_Image_o8rlwro8rlwro8rl_czekyi.png",
    description: "Build a trading empire along the historic Silk Road. Manage caravans, negotiate with merchants, navigate political intrigue, and amass wealth across ancient Asia and Europe.",
    rating: 2.1,
    releaseDate: "2024-03-25",
    developer: "Merchant Prince Studios",
    publisher: "Trade Winds Games",
    tags: ["Strategy", "Trading", "Economic", "Historical"],
    isFree: false,
  },
  {
    id: 60,
    title: "Alien Invasion Tactics",
    price: 8.48,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053516/Gemini_Generated_Image_o2xno2o2xno2o2xn_gzxezw.png",
    description: "Lead Earth's defense against extraterrestrial invasion in this tactical strategy game. Deploy advanced military units, coordinate global defenses, and execute counter-attacks on alien bases.",
    rating: 2.6,
    releaseDate: "2023-12-01",
    developer: "Xeno Defense Studios",
    publisher: "Planetary Defense",
    tags: ["Strategy", "Tactical", "Alien", "Sci-Fi"],
    isFree: false,
  },
  {
    id: 61,
    title: "Fantasy Realms: Kingdom Wars",
    price: 20.66,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053515/Gemini_Generated_Image_h7lybzh7lybzh7ly_wee7ej.png",
    description: "Free-to-play fantasy kingdom management with epic battles. Build your realm, recruit heroes, cast powerful spells, and wage war against rival kingdoms in a magical world.",
    rating: 2.6,
    releaseDate: "2024-06-10",
    developer: "Magic Realm Studios",
    publisher: "Fantasy Kingdom Games",
    tags: ["Strategy", "Fantasy", "Kingdom", "Free to Play"],
    isFree: false,
  },
  {
    id: 62,
    title: "Naval Warfare: Pacific Fleet",
    price: 115.53,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053513/Gemini_Generated_Image_cw975jcw975jcw97_nofsgg.png",
    description: "Command powerful naval fleets in World War II Pacific Theater. Control battleships, carriers, and submarines in realistic naval combat with strategic depth and historical accuracy.",
    rating: 2.1,
    releaseDate: "2024-04-05",
    developer: "Fleet Command Studios",
    publisher: "Naval War Games",
    tags: ["Strategy", "Naval", "WWII", "Historical"],
    isFree: false,
  },
  {
    id: 63,
    title: "Underground Resistance",
    price: 338.56,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053511/Gemini_Generated_Image_42r11b42r11b42r1_ksadnu.png",
    description: "Lead a resistance movement against an oppressive regime in this stealth strategy game. Recruit operatives, plan sabotage missions, and coordinate underground networks to overthrow the dictatorship.",
    rating: 2.9,
    releaseDate: "2023-10-20",
    developer: "Resistance Studios",
    publisher: "Revolution Games",
    tags: ["Strategy", "Stealth", "Resistance", "Tactical"],
    isFree: false,
  },
  {
    id: 64,
    title: "Terraform Mars: Red Planet",
    price: 0,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053509/Gemini_Generated_Image_40licc40licc40li_yifsfp.png",
    description: "Transform Mars into a habitable world in this hard sci-fi strategy game. Manage atmospheric terraforming, build colonies, research technologies, and overcome the harsh Martian environment.",
    rating: 4.5,
    releaseDate: "2024-07-15",
    developer: "Red Planet Studios",
    publisher: "Space Colonization Games",
    tags: ["Strategy", "Sci-Fi", "Terraforming", "Mars"],
    isFree: true,
  },
  {
    id: 65,
    title: "Ancient Empires: Alexander",
    price: 171.27,
    category: "strategy",
    imageUrl: "https://res.cloudinary.com/dhggmrfe1/image/upload/v1771053508/Gemini_Generated_Image_spbi08spbi08spbi_o2des8.png",
    description: "Conquer the known world as Alexander the Great in this grand historical strategy game. Lead Macedonian armies, manage empire expansion, and forge one of history's greatest empires through tactical brilliance.",
    rating: 3.2,
    releaseDate: "2024-02-28",
    developer: "Historical Strategy Works",
    publisher: "Empire Builder Games",
    tags: ["Strategy", "Historical", "Alexander", "Grand Strategy"],
    isFree: false,
  },
];
