export const allProducts = [
  {
    id: 1,
    title: "Cyberpunk 2077",
    price: 59.99,
    category: "strategy",
    imageUrl: "https://placehold.co/300x400",
    description: "Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Improved and featuring all-new free additional content, customize your character and playstyle as you take on jobs, build a reputation, and unlock upgrades.",
    rating: 4.5,
    releaseDate: "2020-12-10",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    tags: ["Action", "RPG", "Open World", "Sci-Fi"],
    isFree: false,
  },
  {
    id: 2,
    title: "GTA V",
    price: 29.99,
    category: "strategy",
    imageUrl: "https://placehold.co/300x400",
    description: "Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the award-winning world of GTA V with a massive range of options for customization.",
    rating: 4.8,
    releaseDate: "2015-04-14",
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    tags: ["Action", "Adventure", "Open World"],
    isFree: false,
  },
  {
    id: 3,
    title: "Far Cry 6",
    price: 49.99,
    category: "strategy",
    imageUrl: "https://placehold.co/300x400",
    description: "Welcome to Yara, a tropical paradise frozen in time. As dictator Antón Castillo intends to restore his nation back to its former glory by any means necessary, you'll play as Dani Rojas, a local Yaran, fighting alongside a modern-day guerrilla revolution to liberate your nation.",
    rating: 4.2,
    releaseDate: "2021-10-07",
    developer: "Ubisoft Toronto",
    publisher: "Ubisoft",
    tags: ["Action", "Shooter", "Open World"],
    isFree: false,
  },
  {
    id: 4,
    title: "God of War",
    price: 49.99,
    category: "action",
    imageUrl: "https://placehold.co/300x400",
    description: "God of War is an action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment. It is eighth installment in the God of War series.",
    rating: 4.9,
    releaseDate: "2018-04-20",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    tags: ["Action", "Adventure", "Hack and Slash"],
    isFree: false,
  },
  {
    id: 5,
    title: "Spider-Man",
    price: 39.99,
    category: "action",
    imageUrl: "https://placehold.co/300x400",
    description: "Marvel's Spider-Man is an action-adventure game developed by Insomniac Games and published by Sony Interactive Entertainment, based on the Marvel Comics superhero Spider-Man.",
    rating: 4.7,
    releaseDate: "2018-09-07",
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    tags: ["Action", "Adventure", "Superhero"],
    isFree: false,
  },
  {
    id: 6,
    title: "Red Dead Redemption 2",
    price: 59.99,
    category: "action",
    imageUrl: "https://placehold.co/300x400",
    description: "Red Dead Redemption 2 is an action-adventure game developed and published by Rockstar Games. It is third entry in the Red Dead series and a prequel to 2010 game Red Dead Redemption.",
    rating: 4.8,
    releaseDate: "2018-10-26",
    developer: "Rockstar Studios",
    publisher: "Rockstar Games",
    tags: ["Action", "Adventure", "Open World"],
    isFree: false,
  },
  {
    id: 7,
    title: "Forza Horizon 5",
    price: 59.99,
    category: "racing",
    imageUrl: "https://placehold.co/300x400",
    description: "Forza Horizon 5 is a 2021 racing game developed by Playground Games and published by Xbox Game Studios. It is fifth Forza Horizon title and twelfth main installment in the Forza series.",
    rating: 4.6,
    releaseDate: "2021-11-09",
    developer: "Playground Games",
    publisher: "Xbox Game Studios",
    tags: ["Racing", "Open World", "Simulation"],
    isFree: false,
  },
  {
    id: 8,
    title: "Need for Speed",
    price: 39.99,
    category: "racing",
    imageUrl: "https://placehold.co/300x400",
    description: "Need for Speed is a racing video game franchise published by Electronic Arts and currently developed by Criterion Games. The series generally centers around illicit street racing.",
    rating: 4.1,
    releaseDate: "2022-11-18",
    developer: "Criterion Games",
    publisher: "Electronic Arts",
    tags: ["Racing", "Action", "Sports"],
    isFree: false,
  },
  {
    id: 9,
    title: "Mario Kart 8",
    price: 49.99,
    category: "racing",
    imageUrl: "https://placehold.co/300x400",
    description: "Mario Kart 8 is a kart racing game developed and published by Nintendo. It is eighth installment in the Mario Kart series.",
    rating: 4.4,
    releaseDate: "2014-05-29",
    developer: "Nintendo EAD",
    publisher: "Nintendo",
    tags: ["Racing", "Casual", "Multiplayer"],
    isFree: false,
  },
  {
    id: 10,
    title: "NBA 2K24",
    price: 59.99,
    category: "sports",
    imageUrl: "https://placehold.co/300x400",
    description: "NBA 2K24 is a basketball simulation video game developed by Visual Concepts and published by 2K. It is the 25th installment in the NBA 2K franchise.",
    rating: 4.0,
    releaseDate: "2023-09-08",
    developer: "Visual Concepts",
    publisher: "2K Sports",
    tags: ["Sports", "Basketball", "Simulation"],
    isFree: false,
  },
  {
    id: 11,
    title: "FIFA 24",
    price: 59.99,
    category: "sports",
    imageUrl: "https://placehold.co/300x400",
    description: "EA Sports FC 24 is a football simulation video game developed by EA Vancouver and EA Romania and published by Electronic Arts. It is 31st installment of FIFA series.",
    rating: 3.8,
    releaseDate: "2023-09-29",
    developer: "EA Vancouver",
    publisher: "Electronic Arts",
    tags: ["Sports", "Simulation", "Football"],
    isFree: false,
  },
  {
    id: 12,
    title: "Madden 24",
    price: 59.99,
    category: "sports",
    imageUrl: "https://placehold.co/300x400",
    description: "Madden NFL 24 is an American football video game developed by EA Tiburon and published by Electronic Arts. It is the 35th installment in the Madden NFL series.",
    rating: 3.9,
    releaseDate: "2023-08-18",
    developer: "EA Tiburon",
    publisher: "Electronic Arts",
    tags: ["Sports", "American Football", "Simulation"],
    isFree: false,
  },
  {
    id: 13,
    title: "Elden Ring",
    price: 59.99,
    category: "rpg",
    imageUrl: "https://placehold.co/300x400",
    description: "Elden Ring is an action role-playing game developed by FromSoftware and published by Bandai Namco Entertainment. It was directed by Hidetaka Miyazaki.",
    rating: 4.8,
    releaseDate: "2022-02-25",
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    tags: ["Action", "RPG", "Open World", "Fantasy"],
    isFree: false,
  },
  {
    id: 14,
    title: "The Witcher 3",
    price: 39.99,
    category: "rpg",
    imageUrl: "https://placehold.co/300x400",
    description: "The Witcher 3: Wild Hunt is an action role-playing game developed and published by CD Projekt. It is the sequel to The Witcher 2: Assassins of Kings.",
    rating: 4.7,
    releaseDate: "2015-05-19",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    tags: ["Action", "RPG", "Open World", "Fantasy"],
    isFree: false,
  },
  {
    id: 15,
    title: "Skyrim",
    price: 29.99,
    category: "rpg",
    imageUrl: "https://placehold.co/300x400",
    description: "The Elder Scrolls V: Skyrim is an action role-playing game developed by Bethesda Game Studios and published by Bethesda Softworks. It is the fifth main installment in The Elder Scrolls series.",
    rating: 4.6,
    releaseDate: "2011-11-11",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    tags: ["Action", "RPG", "Open World", "Fantasy"],
    isFree: false,
  },
  {
    id: 16,
    title: "Call of Duty",
    price: 69.99,
    category: "shooting",
    imageUrl: "https://placehold.co/300x400",
    description: "Call of Duty is a first-person shooter video game franchise published by Activision. The franchise began with the release of Call of Duty in 2003.",
    rating: 4.3,
    releaseDate: "2003-10-29",
    developer: "Infinity Ward",
    publisher: "Activision",
    tags: ["Shooter", "Action", "Multiplayer"],
    isFree: false,
  },
  {
    id: 17,
    title: "Valorant",
    price: 0,
    category: "shooting",
    imageUrl: "https://placehold.co/300x400",
    description: "Valorant is a free-to-play first-person hero shooter developed and published by Riot Games, for Microsoft Windows. The game features a character-based tactical shooter with elements of hero shooters.",
    rating: 4.4,
    releaseDate: "2020-06-02",
    developer: "Riot Games",
    publisher: "Riot Games",
    tags: ["Shooter", "Tactical", "Multiplayer"],
    isFree: true,
  },
  {
    id: 18,
    title: "Overwatch 2",
    price: 0,
    category: "shooting",
    imageUrl: "https://placehold.co/300x400",
    description: "Overwatch 2 is a free-to-play first-person shooter game developed and published by Blizzard Entertainment. It is a sequel to 2016 game Overwatch.",
    rating: 4.2,
    releaseDate: "2022-10-04",
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    tags: ["Shooter", "Hero Shooter", "Multiplayer"],
    isFree: true,
  },
  {
    id: 101,
    title: "MW II",
    price: 69.99,
    category: "shooting",
    imageUrl: "https://placehold.co/300x400",
    description: "Call of Duty: Modern Warfare II is a 2022 first-person shooter game developed by Infinity Ward and published by Activision. It is a sequel to 2019 reboot of Modern Warfare series.",
    rating: 4.3,
    releaseDate: "2022-10-28",
    developer: "Infinity Ward",
    publisher: "Activision",
    tags: ["Shooter", "Action", "Multiplayer"],
    isFree: false,
  },
  {
    id: 103,
    title: "Far Cry 5",
    price: 29.99,
    category: "shooting",
    imageUrl: "https://placehold.co/300x400",
    description: "Far Cry 5 is a 2018 first-person shooter game developed by Ubisoft Montreal and Ubisoft Toronto and published by Ubisoft. It is fifth main installment in Far Cry series.",
    rating: 4.4,
    releaseDate: "2018-03-27",
    developer: "Ubisoft Montreal",
    publisher: "Ubisoft",
    tags: ["Action", "Shooter", "Open World"],
    isFree: false,
  },
];
